### ISSUE TITLE
Applying the rk3399-pcie-phy on Nanopi Neo4

### ISSUE THREAD

**Issue by disablewong** [andrewz1/rk3399-pcie-phy#1]
Hello Andrew, thanks for your hard works to iron out the long time headache of rk3399 pcie interface!
I tried to apply your patch to my nanopi neo4 running on armbian of kernel 6.1.70-current-rockchip64.

The patch was added sucessfully and after reboot, the "PCIe link training gen1 timeout" error was gone.
However, the new error pop-up as below:

root@nanopineo4:/sys/bus/pci/drivers# dmesg | grep -e pci -e PCI 
[    0.008791] PCI/MSI: /interrupt-controller@fee00000/interrupt-controller@fee20000 domain created
[    0.755027] PCI: CLS 0 bytes, default 64
[   17.124291] rockchip-pcie f8000000.pcie: host bridge /pcie@f8000000 ranges:
[   17.124406] rockchip-pcie f8000000.pcie:      MEM 0x00fa000000..0x00fbdfffff -> 0x00fa000000
[   17.124459] rockchip-pcie f8000000.pcie:       IO 0x00fbe00000..0x00fbefffff -> 0x00fbe00000
[   17.125888] platform f8000000.pcie: deferred probe pending

And the pcie interface was not detected either.
Do you have any idea on this problem? 
I was trying to add a nvme 2.5Gbps NIC to the nanopi neo 4 pcie port.

**Comment by andrewz1** [comment]
Hello @disablewong

As I can see NEO4 does not contain onboard hardware, connected to PCIE bus and only have pins for ext connection. So standard device tree also does not contains any device descriptions except controller itself and phy (and disabled ep). You provides only 4 strings from dmesg and what you want?

**Comment by disablewong** [comment]
Thanks for your swift reply!
I am sorry for my rudeness and insufficient information.  
I am just enthusiast of SBC and not a programmer/IT personnel so please accept my apology for my unprofessional manner.

I've used the PCIE extension board to get the pcie signals to a NVMe M.2 slot from neo4 headers.
I was able to get pass the PCIe link training gen1 timeout error in Armbian with additon of voltage to the board (~5.5-5.8V) and get the 2.5Gbps NIC working indeed.  But the result was unstable and it would panic after a short period of time. 

Recently I've learnt from recent armbian leaflet #16 and noted that you've created a patch to cure the PCIe link training problem so I would like to try if the patch could solve my problem.

I've tried to compile the armbian image and patch it following the instructions.  Then I've got the above error of pcie: deferred probe pending.
I've run out of clues and searching of this error in google yield few results and no related case for RK3399 SoC...
Therefore I would like to ask if you had encounter such error before and shade some light on what's this error, no offense.

I would like to attached the full dmesg and would be glad if you could advise what other information are needed.
[dmesg_nanopineo4_pcie_deferred_probe_pending.txt](https://github.com/andrewz1/rk3399-pcie-phy/files/13840759/dmesg_nanopineo4_pcie_deferred_probe_pending.txt)


Thanks again!
Vasco

**Comment by andrewz1** [comment]
@disablewong,

You can try to build armbian trunk for your board. This patch merged to main branch https://github.com/armbian/build/pull/6057 
This repo is only prof of concept "how to replace builtin kernel module with external replacement with patch DTB"
